addSbtPlugin("org.portable-scala"        % "sbt-scalajs-crossproject" % "1.0.0")
addSbtPlugin("org.scala-js"              % "sbt-scalajs"              % "1.1.1")
addSbtPlugin("io.indigoengine"           % "sbt-indigo"               % "0.2.0")
addSbtPlugin("org.wartremover"           % "sbt-wartremover"          % "2.4.9")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"             % "0.1.13")
